#+TITLE: My emacs configuration
#+INCLUDE: ~/.emacs.save/org/common_header.org

This is my .emacs configure for emacs27 on CentOS 7.
It depends on the [[https://github.com/syl20bnr/spacemacs/commits/develop][Spacemacs develop branch]].

** My configurations
The =sl-packages-list= record the packages depends.
The =sl-savefile-dir= can change savefile folder out of .emacs.d directory.
#+BEGIN_SRC emacs-lisp :tangle dot-emacs.el
  (defvar sl-savefile-dir (expand-file-name ".emacs.save/" portable-home-dir))
#+END_SRC

If the =sl-modules= file exists, it will be loaded.

For more details, just refer the [[./init.el]].

The [[./dot-emacs-template.el]] is a template for dot-emacs, refer it for details.

*** Integrate with Spacemacs
 Config the spacemacs with follow layers in =.spacemacs=
 #+BEGIN_SRC emacs-lisp :tangle no
   dotspacemacs-configuration-layers sl-configuration-layers
   dotspacemacs-additional-packages sl-packages-list
   dotspacemacs-excluded-packages sl-packages-excluded
   ;; ...
   dotspacemacs-mode-line-theme 'vanilla
 #+end_src
 Then the Spacemacs will follow the variables initilized in =.emacs=.

*** emacs with msys64
Starting emacs-x86_64-mingw64 directly maybe got the PATH without mingw32/64; follow cmds will help to get correct PATH.
#+begin_src shell
  # starting emacs daemon
  c:\msys64\mingw64.exe bash -lc "runemacs --daemon"
  # starting emacs daemon and kill the frame
  c:\msys64\mingw64.exe bash -lc "emacsclientw --alternate-editor= -t --eval '(delete-frame nil 1)'"
  # for starting a client that daemon maybe not exist
  c:\msys64\mingw64.exe bash -lc "emacsclientw -nc --alternate-editor="
  # for just starting an emacsclient
  c:\msys64\mingw64\bin\emacsclient -c
#+end_src
*** an example for .emacs
A =.emacs= can be copied from =dot-emacs-template=, or simplload it as:
#+begin_src emacs-lisp :tangle "dot-emacs.el"
  ;; -*- mode: emacs-lisp; lexical-binding: t -*-
  (when (equal system-type 'windows-nt)   ; more executables from cygwin
    (add-to-list 'exec-path "c:/cygwin64/bin")
    (setenv "PATH" (concat "c:/cygwin64/bin;" (getenv "PATH"))))
  ;; just following the template configuration.
  (locate-user-emacs-file ".cache/") ; FIXME: workaround for `spacemacs-cache-directory'

  (defvar portable-root-dir (expand-file-name ".." invocation-directory))
  (defvar portable-home-dir
    (if (and (null (fboundp 'image-mask-p)) ; try .rootm-*/.emacs for noX build
             (file-exists-p (expand-file-name ".emacs" portable-root-dir)))
        portable-root-dir
      (file-name-directory (file-truename (or load-file-name (buffer-file-name))))))

  (autoload 'when-let "subr-x")
  (let ((init-template
         (expand-file-name ".home.sl/emacs.spacemacs/dot-emacs-template" portable-home-dir)))
    (load init-template)
    (when-let (init-file (locate-file init-template nil '(".el" ".el.gz")))
      (setq user-init-file init-file)))
#+end_src
** Addtional Requirest
If you need support python =live-py-mode=, it requests the =thinter= package, can install by
#+begin_src shell
apt-get install python36-tkinter
#+end_src

Spacemacs use some symbols fonts in ~spacemacs--diminished-minor-modes~, install ~ttf-ancient-fonts-symbola~ or ~adobe-source-han-sans-cn-fonts~ for them.
The fonts depend on ~all-the-icons~ can download with elisp `all-the-icons-install-fonts'.
** Misc notes
*** Use the emacsclient as the default git difftool and mergetool
Edit ~/.gitconfig file, add follow sections to invoke the emacsclient.
#+begin_src conf
  [difftool]
    tool = ediff
    prompt = false
  [difftool "ediff"]
    cmd = emacsclient $([ -z "$INSIDE_EMACS" ]&&echo -t) --eval \"      \
    (let ((fn (lambda ()                                                \
              (add-hook (quote ediff-after-quit-hook-internal)          \
                        (backquote (lambda ()                           \
                           (dolist (buf (list ,ediff-buffer-A           \
                                              ,ediff-buffer-B           \
                                              ,ediff-buffer-C           \
                                              ,ediff-ancestor-buffer))  \
                             (when (bufferp buf) (kill-buffer buf)))    \
                           (delete-frame nil 1)))                       \
                        nil (quote local)))))                           \
    (ediff-files \\\"$LOCAL\\\" \\\"$REMOTE\\\" (list fn)))\"
  [mergetool]
    tool = ediff
    prompt = false
  [mergetool "ediff"]
    cmd = emacsclient $([ -z "$INSIDE_EMACS" ]&&echo -t) --eval \"      \
    (let ((fn (lambda ()                                                \
              (add-hook (quote ediff-after-quit-hook-internal)          \
                        (backquote (lambda ()                           \
                           (dolist (buf (list ,ediff-buffer-A           \
                                              ,ediff-buffer-B           \
                                              ,ediff-buffer-C           \
                                              ,ediff-ancestor-buffer))  \
                             (when (bufferp buf) (kill-buffer buf)))    \
                           (delete-frame nil 1)))                       \
                        nil (quote local)))))                           \
    (if (> (length \\\"$BASE\\\") 0)                                    \
          (ediff-merge-files \\\"$LOCAL\\\" \\\"$REMOTE\\\"             \
             (list fn) \\\"$MERGED\\\")                                 \
        (ediff-merge-files-with-ancestor                                \
            \\\"$LOCAL\\\" \\\"$REMOTE\\\" \\\"$BASE\\\"                \
            (list fn) \\\"$MERGED\\\")))\"
#+end_src
*** Ctrl+Alt_R+X not working for mintty (xterm)
   Report to [[https://github.com/mintty/mintty/issues/1034][mintty#1034 CTRL + ALT_R + F combination does not work]], workaround is following
   [[https://github.com/mintty/mintty/issues/1034#issuecomment-693930315][mintty1034#issuecomment-693930315]] to map ALT_R to ALT_L.
#+begin_src text :tangle "map-alt_r-to-alt_l.reg"
  Windows Registry Editor Version 5.00

  [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]
  "Scancode Map"=hex:00,00,00,00,00,00,00,00,02,00,00,00,38,00,38,e0,00,00,00,00
#+end_src
*** Ctrl+Backspace and Ctrl+Shift+Backspace for mintty
According https://github.com/mintty/mintty/issues/1082, remap both =Ctrl+Back= and =Ctrl+Shift+Back= in =~/.minttyrc=,
and C+?(C+S+/) remap to "M+_" (use `$ showkey -a` to show key sequence).
#+begin_src conf
  KeyFunctions=C+Back:"[127:5u";C+S+Back:"[127:6u";C+S+/:"_";
#+end_src

Then add keymap in =~/.emacs=:
#+begin_src emacs-lisp
  (global-set-key (kbd "\e[127;5u") [C-backspace]) ; mintty < 3.4.5, modifyOtherKeys=1
  (global-set-key (kbd "\e[127;6u") [C-S-backspace])
  (global-set-key (kbd "\e[127:5u") [C-backspace]) ; mintty >= 3.4.5, remap in .minttyrc
  (global-set-key (kbd "\e[127:6u") [C-S-backspace])
#+end_src

** Shortcuts from Windows to Remote
   *shortcut for remote linux host:*
   \cygwin64\bin\cygstart.exe --hide /usr/bin/ssh.exe -XCnf dev "/bin/bash -lc '~/.root/bin/emacsclient\ -c\ -n\ --alternate-editor='"

   *shortcut for WSL:*
   wsl.exe -u sunlin7 -e /bin/bash -lc "~/.root/bin/emacsclient -c -n --alternate-editor="

   *shortcut for mingw64*
   \msys64\mingw64.exe bash -lc "runemacs --daemon"
   \msys64\mingw64\bin\emacsclientw.exe -c

   *shortcut for standalone*
   \emacs-master-x86_64-full\bin\runemacs.exe --daemon
   \emacs-master-x86_64-full\bin\emacsclientw.exe -c
