#!/usr/bin/env bash
if [ -f setup-x86*.exe ] && [ -d http* ]; then
    for x in $(find http* -type d); do
        for y in $(find $x/ -maxdepth 1 -type f -exec ls -1t {} \+ | tail -n+2 ); do
            echo clean $y; rm $y;
        done;
    done;
else
    echo -e "Clean up the cygwin setup directory.\n"\
         "Only avaliable on cygwin setup directory."
fi
