#!/usr/bin/env bash
# Mount remote folder via sshfs on windows
# The WinFsp have to be installed in the system, and the SSHFS-Win in the path
# A example for start this script from cygwin:
# $ cygstart.exe --hide ~/.home.sl/tools/sshfsw user@IP: Z: -ovolname=v36 -oIdentityFile="<PATH>/.ssh/id_rsa"
set -x
export PATH=/cygdrive/c/temp/SSHFS-Win/bin:$PATH
while true; do
    sshfs "$@" \
             -odebug -ologlevel=debug1 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null \
             -oidmap=user -ouid=-1 -ogid=-1 -oumask=000 -ocreate_umask=000 -omax_readahead=1GB -oallow_other \
             -olarge_read -okernel_cache -ofollow_symlinks -oPreferredAuthentications=publickey
    sleep 5;
done
